---
- name: adding users using loop
  hosts: all
  vars:
    users:
      - jomo
      - kolo
      - bolo
  
  tasks:
    - name: adding users
      user:
        name: "{{ items }}"
        state: present
      loop: "{{ users }}"      
        
